version: '3.8'

services:
  web:
    build: .
    network_mode: "host"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/Media
    environment:
      - SECRET_KEY=${SECRET_KEY:-fuM2OPz4i13m6DbGIO8sQ1rxRieZ5JVYY}
      - DEBUG=${DEBUG:-False}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1,157.245.227.236}
      - DB_NAME=${DB_NAME:-shipping_management}
      - DB_USER=${DB_USER:-kaluu}
      - DB_PASSWORD=${DB_PASSWORD:-kAluu@2025Express}
      - DB_HOST=${DB_HOST:-127.0.0.1}
      - DB_PORT=${DB_PORT:-5432}
    command: bash -c "python manage.py runserver 0.0.0.0:8008"
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:
